# https://docs.github.com/pt/actions/automating-builds-and-tests/building-and-testing-java-with-maven
name: Cucumber

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop
      - 'feature/**'
    tags:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git repository
        uses: actions/checkout@v3

      - name: Configurando Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Configure WebDriver for Chrome
        run:  |
          apt list --installed
          sudo apt purge google-chrome-stable
          sudo apt purge chromium-browser
          sudo apt install -y chromium-browser
          pip install requests beautifulsoup4 pandas webdriver-manager selenium

      - name: Executando Test
        run: |
          mvn test
          'https://mickhill-qa.github.io/treinamento-cucumber-hapvida/feature-overview.html'

      - name: Gerando Relatorio
        run: mvn verify -DskipTests

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload arquivos
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/cucumber-reports/cucumber-html-reports'

      - name: Deploy arquivos no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
